#!/bin/bash -l

#
ln -s ../../../pseudo/fhi/Si.cpi ./01-scf/Si_POT.DAT
#
ln -s ../01-scf/Si_POT.DAT ./02-wfn
ln -s ../01-scf/CD ./02-wfn
#
ln -s ../01-scf/Si_POT.DAT ./03-wfnq
ln -s ../01-scf/CD ./03-wfnq
#
ln -s ../01-scf/Si_POT.DAT ./04-wfn_co
ln -s ../01-scf/CD ./04-wfn_co
#
ln -s ../01-scf/Si_POT.DAT ./05-wfn_fi
ln -s ../01-scf/CD ./05-wfn_fi
#
ln -s ../01-scf/Si_POT.DAT ./06-wfnq_fi
ln -s ../01-scf/CD ./06-wfnq_fi
#
ln -s ../01-scf/Si_POT.DAT ./07-path
ln -s ../01-scf/CD ./07-path
#
ln -s ../PARATEC/02-wfn/WFN ../07-epsilon
ln -s ../PARATEC/03-wfnq/WFN ../07-epsilon/WFNq
#
ln -s ../PARATEC/04-wfn_co/vxc.dat ../08-sigma
ln -s ../PARATEC/04-wfn_co/RHO ../08-sigma
ln -s ../PARATEC/04-wfn_co/WFN ../08-sigma/WFN_inner
ln -s ../07-epsilon/eps0mat ../08-sigma
ln -s ../07-epsilon/epsmat ../08-sigma
ln -s ../07-epsilon/eps0mat.h5 ../08-sigma
ln -s ../07-epsilon/epsmat.h5 ../08-sigma
#
ln -s ../PARATEC/04-wfn_co/WFN ../09-kernel/WFN_co
ln -s ../07-epsilon/eps0mat ../09-kernel
ln -s ../07-epsilon/epsmat ../09-kernel
ln -s ../07-epsilon/eps0mat.h5 ../09-kernel
ln -s ../07-epsilon/epsmat.h5 ../09-kernel
#
ln -s ../PARATEC/04-wfn_co/WFN ../10-absorption/WFN_co
ln -s ../PARATEC/05-wfn_fi/WFN ../10-absorption/WFN_fi
ln -s ../PARATEC/06-wfnq_fi/WFN ../10-absorption/WFNq_fi
ln -s ../07-epsilon/eps0mat ../10-absorption
ln -s ../07-epsilon/epsmat ../10-absorption
ln -s ../07-epsilon/eps0mat.h5 ../10-absorption
ln -s ../07-epsilon/epsmat.h5 ../10-absorption
ln -s ../09-kernel/bsedmat ../10-absorption
ln -s ../09-kernel/bsexmat ../10-absorption
ln -s ../09-kernel/bsemat.h5 ../10-absorption
#
ln -s ../PARATEC/04-wfn_co/WFN ../12-inteqp/WFN_co
ln -s ../PARATEC/07-path/WFN ../12-inteqp/WFN_fi
