#!/bin/bash -l

#
ln -s ../../../pseudo/fhi/C.cpi ./1-scf/C_POT.DAT
#
ln -s ../1-scf/C_POT.DAT ./2-wfn
ln -s ../1-scf/CD ./2-wfn
#
ln -s ../1-scf/C_POT.DAT ./3-wfn_fi
ln -s ../1-scf/CD ./3-wfn_fi
#
ln -s ../PARATEC/3-wfn_fi/WFN ../4-epsilon_0
ln -s ../PARATEC/3-wfn_fi/WFN ../4-epsilon_0/WFNq
#
ln -s ../PARATEC/2-wfn/WFN ../5-epsilon
ln -s ../PARATEC/2-wfn/WFN ../5-epsilon/WFNq
#
ln -s ../PARATEC/2-wfn/vxc.dat ../6-sigma
ln -s ../PARATEC/2-wfn/RHO ../6-sigma
ln -s ../PARATEC/2-wfn/WFN ../6-sigma/WFN_inner
ln -s ../4-epsilon_0/eps0mat ../6-sigma
ln -s ../5-epsilon/epsmat ../6-sigma
ln -s ../4-epsilon_0/eps0mat.h5 ../6-sigma
ln -s ../5-epsilon/epsmat.h5 ../6-sigma
#
ln -s ../PARATEC/2-wfn/WFN ../7-kernel/WFN_co
ln -s ../4-epsilon_0/eps0mat ../7-kernel
ln -s ../5-epsilon/epsmat ../7-kernel
ln -s ../4-epsilon_0/eps0mat.h5 ../7-kernel
ln -s ../5-epsilon/epsmat.h5 ../7-kernel
#
ln -s ../PARATEC/2-wfn/WFN ../8-absorption/WFN_co
ln -s ../PARATEC/3-wfn_fi/WFN ../8-absorption/WFN_fi
ln -s ../4-epsilon_0/eps0mat ../8-absorption
ln -s ../5-epsilon/epsmat ../8-absorption
ln -s ../4-epsilon_0/eps0mat.h5 ../8-absorption
ln -s ../5-epsilon/epsmat.h5 ../8-absorption
ln -s ../7-kernel/bsedmat ../8-absorption
ln -s ../7-kernel/bsexmat ../8-absorption
ln -s ../7-kernel/bsemat.h5 ../8-absorption
#
