#!/bin/bash -l
#
cd Wannier
cd ./14-DFT
rm -rf *.wout
rm -rf *_band.*
rm -rf *.chk
unlink MoS2.amn
unlink MoS2.eig
unlink MoS2.mmn
echo "Wannier/14-DFT DONE."
cd ..
#
cd ./15-GW
rm -rf *.wout
rm -rf *_band.*
rm -rf *.chk
unlink MoS2.amn
unlink MoS2.eig
unlink MoS2.mmn
echo "Wannier/15-GW DONE."
cd ..
cd ..
