#!/bin/bash -l
#SBATCH --partition=debug
#SBATCH --nodes=20
#SBATCH --time=00:30:00
#SBATCH --job-name=my_job
#SBATCH --license=SCRATCH
#SBATCH -C haswell
#SBATCH --ntasks-per-node=32

# Edit these lines as needed
BGW_BIN_DIR=
KERNEL="${BGW_BIN_DIR}/kernel.cplx.x"
ABSORPTION="${BGW_BIN_DIR}/absorption.cplx.x"
export OMP_NUM_THREADS=1
MPIRUN="srun "

#
cd ./16-kernel
$MPIRUN $KERNEL &> ./kernel.out
echo "16-kernel DONE."
cd ..
#
cd ./17-absorption
$MPIRUN $ABSORPTION &> ./absorption.out
echo "17-absorption DONE."
cd ..
