#!/bin/bash -l
#SBATCH --partition=debug
#SBATCH --nodes=1
#SBATCH --time=00:30:00
#SBATCH --job-name=my_job
#SBATCH --license=SCRATCH
#SBATCH -C haswell
#SBATCH --ntasks-per-node=1

# Edit these lines as needed
WAN_BIN_DIR="/global/homes/m/mwu/softwares/Wannier90/Wannier90_3.1.0_dev"
WAN90="${WAN_BIN_DIR}/wannier90.x"
export OMP_NUM_THREADS=1
MPIRUN="srun "

#
cd Wannier
cd ./14-DFT
ln -sf ../../ESPRESSO/09-wannier/MoS2.amn .
ln -sf ../../ESPRESSO/09-wannier/MoS2.mmn .
ln -sf ../../ESPRESSO/09-wannier/MoS2.eig .
$MPIRUN $WAN90 MoS2
echo "Wannier/14-DFT DONE."
cd ..
#
cd ./15-GW
ln -sf ../../ESPRESSO/09-wannier/MoS2.amn .
ln -sf ../../ESPRESSO/09-wannier/MoS2.mmn .
ln -sf ../../13-sig2wan/MoS2.eig .
$MPIRUN $WAN90 MoS2
echo "Wannier/15-GW DONE."
cd ..
cd ..
