#!/bin/bash -l
#
cd ./10-epsilon_subsampling
rm -rf eps0mat.h5
rm -rf epsmat.h5
rm -rf epsilon.log
rm -rf epsilon.out
rm -rf chi_converge.dat
unlink WFN
unlink WFNq
echo "10-epsilon_subsampling DONE."
cd ..
#
cd ./11-epsilon_co
rm -rf eps0mat.h5
rm -rf epsmat.h5
rm -rf epsilon.log
rm -rf epsilon.out
rm -rf chi_converge.dat
unlink WFN
unlink WFNq
echo "11-epsilon_co DONE."
cd ..
#
cd ./12-sigma
rm -rf ch_converge.dat
rm -rf checkbz.log
rm -rf eqp0.dat
rm -rf eqp1.dat
rm -rf sigma.out
rm -rf sigma_hp.log
rm -rf x.dat
unlink WFN_inner
unlink RHO
unlink VXC
unlink eps0mat.5
unlink epsmat.h5
unlink eps0mat
unlink epsmat
unlink subweight.dat
echo "12-sigma DONE."
cd ..
#
cd ./13-sig2wan
rm -rf MoS2.eig
rm -rf sig2wan.out
unlink MoS2.nnkp
unlink sigma_hp.log
echo "13-sig2wan DONE."
cd ..
