#!/bin/bash -l

#
ln -s ../../../pseudo/ld1/C.UPF ./1-scf
#
mkdir ./2-wfn/swcnt_5-5.save
ln -s ../1-scf/C.UPF ./2-wfn
ln -s ../../1-scf/swcnt_5-5.save/data-file.xml ./2-wfn/swcnt_5-5.save
ln -s ../../1-scf/swcnt_5-5.save/charge-density.dat ./2-wfn/swcnt_5-5.save
#
mkdir ./3-wfn_fi/swcnt_5-5.save
ln -s ../1-scf/C.UPF ./3-wfn_fi
ln -s ../../1-scf/swcnt_5-5.save/data-file.xml ./3-wfn_fi/swcnt_5-5.save
ln -s ../../1-scf/swcnt_5-5.save/charge-density.dat ./3-wfn_fi/swcnt_5-5.save
#
ln -s ../ESPRESSO/3-wfn_fi/wfn.complex ../4-epsilon_0/WFN
ln -s ../ESPRESSO/3-wfn_fi/wfn.complex ../4-epsilon_0/WFNq
#
ln -s ../ESPRESSO/2-wfn/wfn.complex ../5-epsilon/WFN
ln -s ../ESPRESSO/2-wfn/wfn.complex ../5-epsilon/WFNq
#
ln -s ../ESPRESSO/2-wfn/vxc.dat ../6-sigma/vxc.dat
ln -s ../ESPRESSO/2-wfn/rho.complex ../6-sigma/RHO
ln -s ../ESPRESSO/2-wfn/wfn.complex ../6-sigma/WFN_inner
ln -s ../4-epsilon_0/eps0mat ../6-sigma
ln -s ../5-epsilon/epsmat ../6-sigma
ln -s ../4-epsilon_0/eps0mat.h5 ../6-sigma
ln -s ../5-epsilon/epsmat.h5 ../6-sigma
#
ln -s ../ESPRESSO/2-wfn/wfn.complex ../7-kernel/WFN_co
ln -s ../4-epsilon_0/eps0mat ../7-kernel
ln -s ../5-epsilon/epsmat ../7-kernel
ln -s ../4-epsilon_0/eps0mat.h5 ../7-kernel
ln -s ../5-epsilon/epsmat.h5 ../7-kernel
#
ln -s ../ESPRESSO/2-wfn/wfn.complex ../8-absorption/WFN_co
ln -s ../ESPRESSO/3-wfn_fi/wfn.complex ../8-absorption/WFN_fi
ln -s ../4-epsilon_0/eps0mat ../8-absorption
ln -s ../5-epsilon/epsmat ../8-absorption
ln -s ../4-epsilon_0/eps0mat.h5 ../8-absorption
ln -s ../5-epsilon/epsmat.h5 ../8-absorption
ln -s ../7-kernel/bsedmat ../8-absorption
ln -s ../7-kernel/bsexmat ../8-absorption
ln -s ../7-kernel/bsemat.h5 ../8-absorption
#
