#!/bin/bash -l
#
BGW_BIN_DIR=/global/cscratch1/sd/mwu/BGW_commit/BerkeleyGW/bin
KGRID="${BGW_BIN_DIR}/kgrid.x"
#
cd ./00-kgrid
$KGRID ./WFN.in ./WFN.out ./WFN.log
$KGRID ./WFN_co.in ./WFN_co.out ./WFN_co.log
$KGRID ./WFNq_co.in ./WFNq_co.out ./WFNq_co.log
$KGRID ./WFN_fi.in ./WFN_fi.out ./WFN_fi.log
$KGRID ./WFNq_fi.in ./WFNq_fi.out ./WFNq_fi.log
cd ..
