#!/bin/bash -l

#
cd 01-scf
ln -s ../../../pseudo/scan/Si.SCAN.UPF Si.UPF  
cd ..

for d in 0{2..5}*/; do
  mkdir -p $d/silicon.save
  ln -sf ../01-scf/Si.UPF $d/
  ln -sf ../../01-scf/silicon.save/data-file-schema.xml $d/silicon.save
  ln -sf ../../01-scf/silicon.save/charge-density.dat $d/silicon.save
  ln -sf ../../01-scf/silicon.save/ekin-density.dat $d/silicon.save
done

#
cd ..
cd 07-epsilon
ln -s ../ESPRESSO/02-wfn/wfn.cplx WFN
ln -s ../ESPRESSO/03-wfnq/wfn.cplx WFNq
cd ..
#
cd 08-sigma
ln -s ../ESPRESSO/04-wfn_co/kih.dat kih.dat
ln -s ../ESPRESSO/04-wfn_co/rho.cplx RHO
ln -s ../ESPRESSO/04-wfn_co/wfn.cplx WFN_inner
ln -s ../07-epsilon/eps0mat .
ln -s ../07-epsilon/epsmat .
ln -s ../07-epsilon/eps0mat.h5 .
ln -s ../07-epsilon/epsmat.h5 .
cd ..
#
cd 09-inteqp
ln -s ../ESPRESSO/04-wfn_co/wfn.cplx WFN_co
ln -s ../ESPRESSO/05-path/wfn.cplx WFN_fi
cd ..
#
