#!/bin/bash -l
#SBATCH -t 00:30:00
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -n 32
#SBATCH -c 1

# The following paths work on NERSC/Cori1
module load paratec
PARATEC="paratec.mpi"
MPIRUN="srun -n 32 -c 1"
export OMP_NUM_THREADS=1

# Or, specify here the path:
#PARATEC="$HOME/paratecSGL/bin/paratec.mpi"
# Put argument for number of procs here too if needed, e.g. -n 8
#MPIRUN="mpirun"
#
cd ./1-scf
$MPIRUN $PARATEC
cd ..
#
cd ./2-wfn
$MPIRUN $PARATEC
cd ..
#
cd ./3-wfnq
$MPIRUN $PARATEC
cd ..
#
cd ./4-wfn_fi
$MPIRUN $PARATEC
cd ..
#
